### ISSUE TITLE
EMR recreates resources when master_instance_group_instance_count  is greater than 1

### ISSUE THREAD

**Issue by homiakos** [cloudposse/terraform-aws-emr-cluster#15]
## Describe the Bug

If you specify a value greater than one, then the cluster is recreated.

I think the problem is in the terraform itself:
https://github.com/terraform-providers/terraform-provider-aws/issues/10446

  But now it would be nice to warn users about this
The problem is reproduced with
core_instance_group_ebs_volumes_per_instance
master_instance_group_ebs_volumes_per_instance

## Expected Behavior
To warn that now it is worth using only the default value, otherwise the cluster will be recreated

## Steps to Reproduce
1. set config
  core_instance_group_ebs_size                   = 32
  core_instance_group_ebs_volumes_per_instance   = 2
  master_instance_group_ebs_size                 = 32
  master_instance_group_ebs_volumes_per_instance = 2
2 . Run apply twice

3. Second apply see:

           - ebs_config { # forces replacement
               - iops                 = 0 -> null
               - size                 = 32 -> null
               - type                 = "gp2" -> null
               - volumes_per_instance = 1 -> null
             }
           + ebs_config { # forces replacement
               + iops                 = 0
               + size                 = 32
               + type                 = "gp2"
               + volumes_per_instance = 2

**Comment by 3h4x** [comment]
Can you describe what was configration first and then to what have you changed it?
I can only guess that the problem is that you changed `volumes_per_instance` from 1 to 2 which is triggering recreation of cluster.
