### ISSUE TITLE
Hardcoded policy_arn's prevents module from working in aws gov cloud

### ISSUE THREAD

**Issue by maheckathorn** [cloudposse/terraform-aws-emr-cluster#6]
On line 290, 325, and 349, policy_arn values are hard coded to values that only exist in AWS commercial:
`  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceRole"
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceforEC2Role"
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceforAutoScalingRole" `

These values are different in aws gov, e.g.:
` arn:aws-us-gov:iam::aws:policy/service-role/AmazonElasticMapReduceRole `

Can you make those values variables with defaults set to the commercial values, so that this module can still be used in aws gov?

**Comment by nitrocode** [comment]
This is now fixed after merging #42 . @maheckathorn please use the latest version.
