### ISSUE TITLE
log_uri forces replacement in example configuration

### ISSUE THREAD

**Issue by yujunz** [cloudposse/terraform-aws-emr-cluster#8]
`log_uri` in example configuration seems forcing replacement.

```
     ~ log_uri                           = "s3n://aws-logs-xxx-us-east-1/" -> "s3://aws-logs-xxx-us-east-1" # forces replacement
```

Should we use format `s3n://...` instead of `s3://...`?

**Comment by aknysh** [comment]
thanks @yujunz 
you can open a PR with your changes, we'll review promptly
